name: hammer_student_attendance
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  flutter_launcher_icons: ^0.13.1
  bot_toast: ^4.1.3
  http: ^1.2.2
  flutter_dotenv: ^5.1.0
  flutter_tts: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21

  flutter_lints: ^4.0.0
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/gif/
    - assets/illustrations/
    - .env